# Please keep AllCops, Bundler, Layout, Style, Metrics groups and then order cops
# alphabetically
#
# References:
#   * https://github.com/bbatsov/ruby-style-guide
#   * https://rubocop.readthedocs.io/
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/master/.rubocop-unstable.yml
AllCops:
  TargetRubyVersion: 2.7
