# Please keep AllCops, Bundler, Layout, Style, Metrics groups and then order cops
# alphabetically
#
# References:
#   * https://github.com/bbatsov/ruby-style-guide
#   * https://rubocop.readthedocs.io/
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/main/.rubocop.yml
AllCops:
  TargetRubyVersion: 3.0

Lint/EmptyBlock:
  Exclude:
    - "./spec/integration/hanami/api/block_spec.rb"
